version: "3.4"
services:
  golem.public.dappnode.eth:
    build:
      context: ./build
      args:
        YA_CORE_VERSION: 0.6.1
        YA_WASI_VERSION: 0.2.2
        YA_VM_VERSION: 0.2.5
    image: "golem.public.dappnode.eth:0.1.0"
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "node_data/:/root/.local/"
    devices:
      - "/dev/kvm:/dev/kvm"
    environment:
      - NODE_NAME=arbiter
      - YA_PAYMENT_NETWORK=mainnet
      - YA_ACCOUNT=0x185196C8C5Dd5729f22315203E09E33c3f7D7680
      - YA_CORE_VERSION=0.6.1
      - YA_WASI_VERSION=0.2.2
      - YA_VM_VERSION=0.2.5
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.golem-clean.schedule: "@daily"
      ofelia.job-exec.golem-clean.command: >-
        find /root/.local/share/ya-provider/exe-unit/cache/ -mtime +7 -type f
        -exec rm {} +
volumes:
  node_data: {}
