version: "3.4"
services:
  ofelia:
    image: "mcuadros/ofelia:latest"
    depends_on:
      - chain
    command: daemon --docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  chain:
    build:
      context: ./build
      args:
        YA_CORE_VERSION: pre-rel-v0.6.6-rc1
        YA_WASI_VERSION: 0.2.2
        YA_VM_VERSION: 0.2.5
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "node_data/:/root/.local/"
    devices:
      - "/dev/kvm:/dev/kvm"
    environment:
      - NODE_NAME=arbiter
      - YA_PAYMENT_NETWORK=mainnet
      - ENABLE_DYNAMIC_RATE=1
      - ENV_DISCOUNT_RATE=
      - YA_ACCOUNT=
      - CPU_HOUR_RATE=
      - ENV_PER_HOUR_RATE=
      - CPU_SHARED_CORES=
      - START_RATE=0
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.golem-clean.schedule: "@daily"
      ofelia.job-exec.golem-clean.command: >-
        find /root/.local/share/ya-provider/exe-unit/cache/ -mtime +7 -type f
        -exec rm {} +
      ofelia.job-exec.golem-median.schedule: "@every 10mins"
      ofelia.job-exec.golem-median.command: /usr/bin/median.sh
    image: "chain.golem.public.dappnode.eth:0.1.0"
volumes:
  node_data: {}
